config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, presence: true, length: { minimum: 1, maximum: 50 }
  validates :email, presence: true, length: { minimum: 1, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  def show

  end

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def edit

  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = "Student was saved successfully."
      redirect_to @student
    else
      render 'new'
    end
  end

  def update

    if @student.update(student_params)
        flash[:notice] = "Student was updated successfully."
        redirect_to @student
    else
        render 'edit'
    end
  end

  def destroy

    @student.destroy
    redirect_to students_path
  end

  private

  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentReg</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= msg %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Student Registration page</h1>


<%= link_to 'Students listing', students_path %> 
<p><%= link_to 'Add new student', new_student_path %></p>

app/views/students/_form.html.erb
<% if @student.errors.any? %>
<h2>The following errors occured</h2>
<ul>
  <% @student.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_with(model: @student, local: true) do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.submit %>
  </p>


<% end %>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= render 'form' %>

<%= link_to 'Cancel and return to students listing', students_path %>

app/views/students/index.html.erb
<h1>Students listing page</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
    <tr>
      <td><%= student.name %></td>
      <td><%= student.email %></td>
      <td><%= link_to 'Show', student_path(student) %></td>
      <td><%= link_to 'Edit', edit_student_path(student) %></td>
      <td><%= link_to 'Delete', student_path(student), method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to 'Add new student', new_student_path %></p>

app/views/students/new.html.erb
<h1>Enter new Student</h1>

<%= render 'form' %>

<%= link_to 'Return to students listing', students_path %>

app/views/students/show.html.erb
<h1>Showing student details</h1>

<p><strong>Name: </strong><%= @student.name %></p>
<p><strong>Email: </strong><%= @student.email %></p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Delete', student_path(@student), method: :delete, data: { confirm: "Are you sure?" } %> |
<%= link_to 'Return to students listing', students_path %>